### ISSUE TITLE
IE11

### ISSUE THREAD

**Issue by zolem** [xxhomey19/infinite-array#2]
Hi, I was using this library to create an infinite array on a web application that rotates through an array of colors. Looks like your typescript is targeting ES6 and possibly using some ES6 features. This is not supported in IE11.

I assume this project was intended to be used in node where that probably is not a problem. Do you know of any similar libraries that might work or is it possible to target a version that IE11 supports? Thanks!

**Comment by homerchen19** [comment]
Hi @zolem,
Did you try [polyfill](https://babeljs.io/docs/en/babel-polyfill/) to compile ES6 libraries? IE11 doesn't support much of ES6, so you can use a transpiler (like `Babel`) to convert your ES6 code to ES5 code that will work in older browsers.

**Comment by zolem** [comment]
I will have to try that. In the meantime I simply wrote a function that essentially does the same thing I just can't use the bracket syntax. Thanks!
